"""Generate constant-case LUTs and independent numerical fixtures; no EDA setup."""
from pathlib import Path
import json, math, random
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'nonlinear/assets'
OUT.mkdir(exist_ok=True)
EXP_PROFILES=[(8,a) for a in (6,7,8)]+[(16,a) for a in (7,8,9,10)]
nearest=lambda x:math.floor(x+0.5)
def exp_table(w,a):
    f=w-4; stride=1<<(w-a); lo=-(1<<(w-1))
    # Unsigned headroom at the knot just ABOVE the signed clamp boundary.
    vals=[min((1<<w)-1,nearest(math.exp((lo+i*stride)/(1<<f))*(1<<f))) for i in range((1<<a)+1)]
    threshold=next(x for x in range(lo,1<<(w-1)) if nearest(math.exp(x/(1<<f))*(1<<f))>(1<<(w-1))-1)
    return vals,threshold
lines=['// Generated by nonlinear/tools/generate.py. Constant logic; no RAM preload.',
 'module exp_lut #(parameter W=16, A=9) (',
 'input logic [A-1:0] addr, output logic [W-1:0] base, delta);','generate']
metrics={}
for w,a in EXP_PROFILES:
    vals,threshold=exp_table(w,a)
    lines += [f'if (W=={w} && A=={a}) begin : lut_{w}_{a}',
      'function automatic [2*W-1:0] lookup(input logic [A-1:0] index);','case (index)']
    for i in range(1<<a):
        active=-(1<<(w-1))+(i<<(w-a)) < threshold
        v,d=(vals[i],vals[i+1]-vals[i]) if active else (0,0)
        if v or d: lines += [f"{a}'d{i}: lookup={{{w}'d{v},{w}'d{d}}};"]
    lines += ["default: lookup='0;",'endcase','endfunction','assign {base,delta}=lookup(addr);','end']
    f=w-4; shift=w-a; hi=(1<<(w-1))-1; errors=[]; model=[]
    for raw in range(-(1<<(w-1)),1<<(w-1)):
        idx=(raw+(1<<(w-1)))>>shift; rem=raw&((1<<shift)-1)
        pred=vals[idx]+(((vals[idx+1]-vals[idx])*rem+(1<<(shift-1)))>>shift if shift else 0)
        pred=hi if raw>=threshold else min(hi,pred)
        exact=min(hi,nearest(math.exp(raw/(1<<f))*(1<<f)))
        errors.append(abs(pred-exact));model.append(pred)
    assert model==sorted(model)
    metrics[f'exp_w{w}_a{a}']={'entries':1<<a,'max_error_lsb':max(errors),
      'mean_error_lsb':sum(errors)/len(errors),'overflow_raw_threshold':threshold}
    (OUT/f'exp_expected_{w}_{a}.hex').write_text(''.join(f'{x:0{w//4}x}\n' for x in model))
    (OUT/f'exp_exact_{w}.hex').write_text(''.join(f'{min(hi,nearest(math.exp(raw/(1<<f))*(1<<f))):0{w//4}x}\n' for raw in range(-(1<<(w-1)),1<<(w-1))))
lines += ['endgenerate','endmodule','',
 'module rsqrt_lut #(parameter A=9, C=18) (',
 'input logic [A-1:0] addr, output logic [C:0] base, delta);','generate']
for a,c in [(7,12),(9,18)]:
    m=a-2
    lines += [f'if (A=={a} && C=={c}) begin : lut_{a}_{c}',
      'function automatic [2*(C+1)-1:0] lookup(input logic [A-1:0] index);','case (index)']
    for i in range(1<<m,1<<a):
        v=nearest((1<<c)/math.sqrt(i/(1<<m)))
        n=nearest((1<<c)/math.sqrt((i+1)/(1<<m)))
        lines += [f"{a}'d{i}: lookup={{{c+1}'d{v},{c+1}'d{v-n}}};"]
    lines += ["default: lookup='0;",'endcase','endfunction','assign {base,delta}=lookup(addr);','end']
lines += ['endgenerate','endmodule','']
def norm_model(v,w,a,c,ib,eps=1):
    f=w-4;mean=sum(x*x for x in v)//len(v)+eps;k=(mean.bit_length()-1)//2
    scaled=(mean<<(a-2+ib))>>(2*k);addr=scaled>>ib;frac=scaled&((1<<ib)-1)
    base=nearest((1<<c)/math.sqrt(addr/(1<<(a-2))))
    nxt=nearest((1<<c)/math.sqrt((addr+1)/(1<<(a-2))))
    coeff=base-(((base-nxt)*frac+(1<<(ib-1)))>>ib)
    shift=c+k-f;hi=(1<<(w-1))-1;lo=-(1<<(w-1));values=[];exacts=[];overflow=False
    for x in v:
        mag=(abs(x)*coeff+(1<<(shift-1)))>>shift;q=-mag if x<0 else mag
        overflow |= q<lo or q>hi;values.append(max(lo,min(hi,q)))
        exact=nearest(abs(x)*(1<<f)/math.sqrt(mean))
        exacts.append(max(lo,min(hi,-exact if x<0 else exact)))
    return values,overflow,max(abs(x-y) for x,y in zip(values,exacts))
for w in (8,16):
    a,c,ib=(7,12,6) if w==8 else (9,18,8)
    scale=1<<(w-4);hi=(1<<(w-1))-1;lo=-(1<<(w-1));rng=random.Random(178+w)
    vectors=[[0]*512,[scale]*512,[-scale]*512,[lo if i%2 else hi for i in range(512)],
      [hi]+[0]*511,[lo]+[0]*511,[1]*512,[lo]*512,[hi]*512,
      [((i%17)-8)*max(1,scale//16) for i in range(512)]]
    vectors += [[rng.randrange(lo,hi+1) for _ in range(512)] for _ in range(10)]
    vectors += [[rng.randrange(-4,5) for _ in range(512)],[1]+[0]*511,
      [hi if i%31==0 else 0 for i in range(512)],[0]*511+[lo]]
    results=[norm_model(v,w,a,c,ib) for v in vectors]
    def pack(v,lanes=32):
        return ''.join(f'{sum((v[j+i]&((1<<w)-1))<<(i*w) for i in range(lanes)):0{w*lanes//4}x}\n' for j in range(0,len(v),lanes))
    (OUT/f'norm_input_{w}.hex').write_text(''.join(pack(v) for v in vectors))
    (OUT/f'norm_expected_{w}.hex').write_text(''.join(pack(v[0]) for v in results))
    (OUT/f'norm_flags_{w}.hex').write_text(''.join(f'{int(v[1]):x}\n' for v in results))
    for n,lanes in [(64,8),(1,1)]:
        small=[v[:n] for v in vectors]
        gold=[norm_model(v,w,a,c,ib) for v in small]
        (OUT/f'norm_input_{w}_{n}_{lanes}.hex').write_text(''.join(pack(v,lanes) for v in small))
        (OUT/f'norm_expected_{w}_{n}_{lanes}.hex').write_text(''.join(pack(v[0],lanes) for v in gold))
        (OUT/f'norm_flags_{w}_{n}_{lanes}.hex').write_text(''.join(f'{int(v[1]):x}\n' for v in gold))
    metrics[f'norm_w{w}']={'vectors':len(vectors),'max_error_lsb':max(r[2] for r in results),
      'lut_reachable_entries':3*(1<<(a-2)),'lut_address_width':a,'coefficient_fraction_width':c,'interpolation_bits':ib}
    # Integrated register program: EXP -> NORM, in-place NORM, high bank,
    # back-to-back NORM. The same fixtures also drive the real top wiring test.
    regs=[[0]*512 for _ in range(8)];regs[0]=vectors[9].copy()
    regs[0][0]=lo;regs[0][511]=hi
    (OUT/f'dispatch_initial_{w}.hex').write_text(pack(regs[0]))
    program=[(5,1,0),(7,2,1),(7,2,2),(5,3,2),(7,7,3),(7,4,7)]
    exp_values=[int(x,16) for x in (OUT/f'exp_expected_{w}_{8 if w==8 else 9}.hex').read_text().split()]
    traces=[];oflags=[]
    for op,dst,src in program:
        if op==5:
            out=[exp_values[x-lo] for x in regs[src]]
            flag=any(x>=(34 if w==8 else 8518) for x in regs[src])
        else:out,flag,_=norm_model(regs[src],w,a,c,ib)
        regs[dst]=out;traces.append(pack(out));oflags.append(int(flag))
    (OUT/f'dispatch_expected_{w}.hex').write_text(''.join(traces))
    (OUT/f'dispatch_flags_{w}.hex').write_text(''.join(f'{x:x}\n' for x in oflags))
    instructions=[(op<<9)|(dst<<6)|src for op,dst,src in program]+[8191]*58
    (OUT/f'dispatch_program_{w}.mem').write_text(''.join(f'{x:013b}\n' for x in instructions))
    # Exercise a normal ADD producer immediately before the nonlinear barrier.
    regs=[[0]*512 for _ in range(8)];regs[0]=vectors[9].copy();regs[0][0]=lo;regs[0][511]=hi
    regs[0]=[((2*x-lo)&((1<<w)-1))+lo for x in regs[0]]
    traces=[];oflags=[]
    for op,dst,src in program:
        if op==5:
            out=[exp_values[x-lo] for x in regs[src]];flag=any(x>=(34 if w==8 else 8518) for x in regs[src])
        else:out,flag,_=norm_model(regs[src],w,a,c,ib)
        regs[dst]=out;traces.append(pack(out));oflags.append(int(flag))
    (OUT/f'mixed_expected_{w}.hex').write_text(''.join(traces))
    (OUT/f'mixed_flags_{w}.hex').write_text(''.join(f'{x:x}\n' for x in oflags))
    instructions=[1<<9]+instructions[:63]
    (OUT/f'mixed_program_{w}.mem').write_text(''.join(f'{x:013b}\n' for x in instructions))
(OUT/'accuracy.json').write_text(json.dumps(metrics,indent=2)+'\n')
print(json.dumps(metrics,indent=2))
