"""Generate checkpoint-independent fixed-point nonlinear tables for RTL.

No application inference is performed. The emitted integer samples are also
checked by the arithmetic unit regression before application execution.
"""
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[2]


def main():
    lines = ["// Generated by tools/llm/generate_tables.py; exp(-i/16) in U25/F24.",
             "function automatic logic [24:0] llm_exp_sample(input logic [8:0] index);",
             "    case (index)"]
    for i in range(257):
        value = round(math.exp(-i / 16) * (1 << 24))
        lines.append(f"        9'd{i}: llm_exp_sample = 25'd{value};")
    lines += ["        default: llm_exp_sample = 0;", "    endcase", "endfunction", ""]
    (ROOT / "Verilog Source code" / "llm_exp_lut.svh").write_text(
        "\n".join(lines), encoding="utf-8", newline="\n")
    lines = ["// Quantile samples of -log(-log(U)), S24/F16; U=(i+0.5)/256.",
             "function automatic logic signed [23:0] llm_gumbel_sample(input logic [7:0] index);",
             "    case (index)"]
    for i in range(256):
        value = round(-math.log(-math.log((i + 0.5) / 256)) * (1 << 16))
        lines.append(f"        8'd{i}: llm_gumbel_sample = 24'sh{value & 0xffffff:06x};")
    lines += ["        default: llm_gumbel_sample = 0;", "    endcase", "endfunction", ""]
    (ROOT / "Verilog Source code" / "llm_gumbel_lut.svh").write_text(
        "\n".join(lines), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
