"""Generate checkpoint-independent fixed-point nonlinear tables for RTL.

No application inference is performed. The emitted integer samples are also
checked by the arithmetic unit regression before application execution.
"""
from pathlib import Path
import math
import argparse

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'Verilog Source code')
    output = parser.parse_args().output_dir
    output.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by tools/llm/generate_tables.py; exp(-i/16) in U25/F24.",
             "module llm_exp_sample(input logic [8:0] index, output logic [24:0] value);",
             "    always_comb begin",
             "    case (index)"]
    for i in range(257):
        value = round(math.exp(-i / 16) * (1 << 24))
        lines.append(f"        9'd{i}: value = 25'd{value};")
    lines += ["        default: value = 0;", "    endcase", "    end", "endmodule", ""]
    (output / "llm_exp_lut.svh").write_text(
        '`ifndef LLM_EXP_SAMPLE_SVH\n`define LLM_EXP_SAMPLE_SVH\n' + "\n".join(lines) + '`endif\n', encoding="utf-8", newline="\n")
    lines = ["// Quantile samples of -log(-log(U)), S24/F16; U=(i+0.5)/256.",
             "module llm_gumbel_sample(input logic [7:0] index, output logic signed [23:0] value);",
             "    always_comb begin",
             "    case (index)"]
    for i in range(256):
        value = round(-math.log(-math.log((i + 0.5) / 256)) * (1 << 16))
        lines.append(f"        8'd{i}: value = 24'sh{value & 0xffffff:06x};")
    lines += ["        default: value = 0;", "    endcase", "    end", "endmodule", ""]
    (output / "llm_gumbel_lut.svh").write_text(
        '`ifndef LLM_GUMBEL_SAMPLE_SVH\n`define LLM_GUMBEL_SAMPLE_SVH\n' + "\n".join(lines) + '`endif\n', encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
